#!/usr/bin/env bash
# This script does many cool things.

echo $$ > /var/run/myscript.pid

trap 'echo I hate the kill command; rm /var/run/myscript.pid; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGKILL $$' SIGINT
trap 'rm /var/run/myscript.pid; kill -SIGKILL $$' SIGQUIT

while (true)
do 
    echo "To infinity and beyond"
done
